config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, :controllers => {
  :sessions      => "users/sessions",
  :registrations => "users/registrations",
  :passwords     => "users/passwords",
  :omniauth_callbacks => "users/omniauth_callbacks"
  }

  get 'welcome/no_data' # ドメイン・バックリンクデータが存在しない場合の仮のペラページ
  get 'welcome/test' # テスト用

  
  resources :domains do
    member do
    end
    
    collection do
      post 'import'
      get 'nglist'
      get 'test'
    end
  end

  resources :backlinks do
    member do
    end
    
    collection do
      post 'import'
    end
  end

  resources :users do
    member do
      post 'pro_upgrade'
    end
    collection do
    end
  end
  
  resources :forums do
    collection do
      get 'message'
    end
  end
 
  resources :replayposts, only: [:new, :create, :edit, :update, :destroy]
  resources :resposts, only: [:show, :create, :edit, :update, :destroy]
  resources :forums, only: [:index, :show, :create, :update, :destroy]
  resources :manage, only: [:index]
  resources :users, only: [:index, :update, :destroy]
  
  resources :domains, only: [:index, :show]

end

app/models/forum.rb
class Forum < ActiveRecord::Base
    has_many :resposts, dependent: :destroy
    has_many :replayposts, dependent: :destroy
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
    before_action :authenticate_user!, only:[:show]
    before_action :no_promember, only: [:show]
    before_action :admin_user, only: [:create, :update, :destroy]
    
    # フォーラムの作成画面を表示する new_forum_path
    # def new
    # end
    
    # フォーラムを作ってデータベースに登録
    def create
        @forum = Forum.new(forum_params)
        @forum.save
        flash[:success] = "フォーラムを作成しました。"
        redirect_to request.referrer || manage_index_path
    end
    
    # 作成したフォーラムの編集画面 edit_forum_path()
    # def edit
    # end
    
    # フォーラムデータ（データベース）を更新する
    def update
        @forum = Forum.find(params[:id])
        @forum.update(title: params[:forum][:title], description: params[:forum][:description])
        flash[:success] = "フォーラムをアップデートしました。"
        redirect_to request.referrer || manage_index_path
    end
    
    # フォーラム一覧の表示 forums_path
    def index
        @forums = Forum.order(created_at: :desc) # 降順
        # 以下は上記と同じ
        # @forums = Forum.all.order(created_at: :desc)
        # @formus = Forum.order(:created_at).reverse_order

    end
    
    # 各フォーラムごとのページを表示 forum_path()
    def show
        @forum = Forum.find(params[:id])
        @respost = Respost.new
        # @resposts = Respost.order(created_at: :desc)
        # @resposts = Respost.order(updated_at: :desc)
        # 以下はkaminari適用
        ## @resposts = Respost.order(updated_at: :desc).page(params[:page]).per(5)
        # @resposts = Respost.order(updated_at: :desc).page(params[:page]).per(5) # 降順
        # @resposts = Respost.where(forum_id: params[:id]).order(updated_at: :desc).page(params[:page]).per(5) # 降順
        @resposts = Respost.where(forum_id: params[:id]).order(replaytime: :desc).page(params[:page]).per(5) # 降順
        @replayposts = Replaypost.all
        @users = User.all
    end
    
    # フォーラムを削除
    def destroy
        @forum = Forum.find(params[:id])
        @forum.destroy
        flash[:success] = "フォーラムを削除しました。"
        redirect_to request.referrer || manage_index_path        
    end

    private
    
    def forum_params
    # params[:forum]のパラメータで title , descriptionのみを許可する。
    # 返り値は ex:) {title: "入力されたtitle" , description: "入力されたdescription" }
    params.require(:forum).permit(:title, :description)
    end

    def admin_user
        redirect_to root_path unless current_user.admin?
    end

    def no_promember
        if !current_user.admin? && !current_user.promember?
           redirect_to message_forums_path
        end
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/index.html.erb
<div class="panel panel-info">
	<div class="panel-heading">
		<h1 class="panel-title">
			<span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
			フォーラム一覧
		</h1>
	</div>
    <div class="panel-body">
        <%# if !current_user.promember? %>
            <p>有料会員様のみフォーラムをご利用できます。
            </p>
        <%# end %>
    </div>
    <div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th width="50%">フォーラムタイトル</th>
            <th>説明</th>
          </tr>
        </thead>
        <tbody>
        <% @forums.each do |t| %>
            <tr>
                <td><h4><%=link_to t.title, forum_path(t.id) %></h4></td>
                <td><%= t.description %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
    </div>
</div>

<%# 自分の投稿や返信に関連するものを表示させる処理 ここから ######################################## %>
<div class="panel panel-info">
	<div class="panel-heading">
		<h1 class="panel-title">
			<span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
			あなたに関するフォーラム及び投稿一覧
		</h1>
	</div>
    <div class="panel-body">
        <!-- 何か説明文を書く -->
    </div>
    <div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th width="50%">フォーラムタイトル</th>
            <th>投稿タイトル</th>
          </tr>
        </thead>
        <tbody>
        <% @forums.each do |t| %>
            <% my_resposts = t.resposts.where(user_id: current_user.id) %><%# 自分の投稿 %>
            <% my_replayposts = t.replayposts.where(user_id: current_user.id) %><%# 自分の返信 %>
            <% if my_resposts.count > 0 || my_replayposts.count > 0 %><%# 自分の投稿または返信があれば %>
                <tr>
                    <td><h4><%=link_to t.title, forum_path(t.id) %></h4></td>
                    <td>
                        <%# resposts = t.resposts %>
                        <% resposts = t.resposts.order(updated_at: :desc) %>
                        <%# replayposts = t.replayposts %>
                        <% respost_count = 1 %><%# 多数該当するrespostがある場合、途中でループを抜けるのでカウントを設定 %>
                        <ul>
                            <% resposts.each do |respost| %><%# 投稿 %>
                                <% break if respost_count > 10 %><%# 10個以上になったらループを抜ける %>
                                <% if (respost.user_id == current_user.id) || (respost.replayposts.where(user_id: current_user.id).count > 0) %>
                                    <% respost_count +=1 %>
                                    <li>
                                        <%= respost.updated_at.strftime("%Y/%m/%d/ %H:%M") %> 
                                        <%= link_to respost.title, respost_path(respost.id) %>
                                    </li>
                                    <hr style="margin:3px 3px;">
                                <% end %>
                            <% end %>
                        </ul>
                    </td>
                </tr>
            <% end %>
        <% end %>
        </tbody>
    </table>
    </div>
</div>
<%# 自分の投稿や返信に関連するものを表示させる処理 ここまで ######################################## %>

app/views/forums/message.html.erb
<div class="panel panel-danger">
	<div class="panel-heading">
		<h1 class="panel-title">
			<span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
			有料会員様のみフォーラムをご利用できます。
		</h1>
	</div>
    <div class="panel-body">
        <p>大変恐れ入りますが、フォーラムのご利用は有料会員様限定のコンテンツとなっております。
        </p>
    </div>
</div>

app/views/forums/new.html.erb
<p>forum new</p>

app/views/forums/show.html.erb
forum_id:<%= @forum.id %><br />
user_id:<%= current_user.id %><br />
@forum.inspect:<%= @forum.inspect %><br />
<hr />

<div class="col-sm-8 col-sm-offset-2">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1 class="panel-title text-center">
    <strong><%= @forum.title %></strong><small class="pull-right">フォーラムタイトル</small>
    </h1>
  </div>
  <div class="panel-body">
    <%= @forum.description %>
  </div>
</div>
</div>

<div class="col-sm-8 col-sm-offset-2">
<div class="panel panel-success">
  <div class="panel-heading">
    <h1 class="panel-title text-center">
    <strong>書き込みフォーム</strong>
    </h1>
  </div>
  <div class="panel-body">
    <% if false %>
        <%# 直接コントローラーとアクションを指定する方法でも可能 %>
        <%= form_for(@respost, :url => {:controller => 'resposts', :action => 'create'}) do |f| %>
            <%= f.label :title, "タイトル" %><br />
            <%= f.text_field :title, class: "input-xlarge" %><br />
            <%= f.label :content, "本文" %><br />
            <%= f.text_area :content, class: "input-xlarge" %><br />
            <%= f.submit class: "btn btn-sm btn-primary" %>
        <% end %>
    <% end %>
    <%= form_for(@respost) do |f| %>
        
        <%= render 'shared/error_messages', object: f.object %><%# バリデーションのエラーメッセージ %>

        <div class="form-group">
            <%= f.hidden_field :replaytime, value: DateTime.now %><%# 最終更新日 %>
            <%= f.hidden_field :forum_id, value: @forum.id %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.label :title, "タイトル" %><br />
            <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :content, "本文" %><br />
            <%= f.text_area :content, class: "form-control", rows: 8 %>
        </div>
        <% if current_user.handlename.present? %>
          <%= f.submit "投稿する", class: "btn btn-sm btn-primary" %>
        <% else %>
            <p>あなたのハンドルネームがまだ設定されていません。<br/>
            投稿する前に以下のページでハンドルネームを設定してください。<br />
            ハンドルネームが設定されている場合、『投稿ボタン』が表示されます。
            </p>
            <%= link_to 'ユーザー情報編集', edit_user_registration_path %>
        <% end %>
    <% end %>
  </div>
</div>
</div>

<%# 投稿された書き込み ここから ####################################################### %>
<% @resposts.each do |t| %>
<div class="col-sm-12">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h1 class="panel-title text-center">
                <strong><%= t.title %></strong> <small><span style="text-decoration:underline;"><%= link_to "リンク", respost_path(t.id) %></span></small><small class="pull-right">post_id:<%= t.id %></small>
            </h1>
        </div>
        <div class="panel-body">
            <% user = @users.find_by(id: t.user_id) %>
            <% if user.present? %><%# 投稿したユーザーの存在をチェック %>
                <div class="col-sm-4">
                    投稿者：<strong><%= user.handlename %></strong> さん
                </div>
            <% else %><%# 投稿者がデータベースに存在しなければ %>
                <div class="col-sm-4">
                    投稿者が退会済です
                </div>            
            <% end %>
            <div class="col-sm-4">
                <%# d = t.created_at %>
                投稿日：<%= t.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %>  
            </div>
            <div class="col-sm-4">
                <% if t.updated_at != t.created_at %><%# 投稿が編集されていれば編集日を表示する %>
                編集日：<%= t.updated_at.strftime("%Y年%m月%d日 %H:%M:%S") %>
                <% end %>
            </div>
            <!-- <p>&nbsp;</p> -->
            <div class="col-sm-12">
                <p>
                    <%= t.content %>
                </p>
            </div>
            <!-- <p>&nbsp;</p> -->
            <div class="col-sm-12">
                <p><%= link_to "返信", new_replaypost_path(forum_id: @forum.id, respost_id: t.id, user_id: current_user.id) %>
                    <% if current_user.id == t.user_id || current_user.admin? %><%# 投稿者本人のみ編集・削除を可能とする %>
                         | <%= link_to "書き込みを編集する",edit_respost_path(t.id) %> | 
                        <%#= link_to "削除", t, class: "btnlink btnlink-danger glyphicon glyphicon-trash",
                            method: :delete, data: {confirm: "本当に削除してもいいですか？"} %>
                        <%# destroyアクションにforum_idというパラメータを渡して、投稿削除後にこのページへリダイレクトさせる %>
                        <%= link_to "削除", respost_path(t.id, forum_id: @forum.id), class: "btnlink btnlink-danger glyphicon glyphicon-trash",
                            method: :delete, data: {confirm: "本当に削除してもいいですか？"} %>
                    <% end %>
                </p>
            </div>

            <%# 返信された書き込み ここから ####################################################### %>
            <% @replaypost = @replayposts.where(respost_id: t.id) %>
            <%# if false %>
            <% @replaypost.each do |replaypost| %>
            <div class="col-sm-12">
                <div class="panel panel-danger">
                    <div class="panel-heading">
                        <h1 class="panel-title text-center">
                            <strong><%= replaypost.title %></strong><small class="pull-right">replay_id:<%= replaypost.id %></small>
                        </h1>
                    </div>
                    <div class="panel-body">
                        <% user = @users.find_by(id: replaypost.user_id) %>
                        <% if user.present? %><%# 投稿したユーザーの存在をチェック %>
                            <div class="col-sm-4">
                                返信者：<strong><%= user.handlename %></strong> さん
                            </div>
                        <% else %><%# 投稿者がデータベースに存在しなければ %>
                            <div class="col-sm-4">
                                返信者が退会済です
                            </div>            
                        <% end %>
                        <div class="col-sm-4">
                            <%# d = t.created_at %>
                            返信日：<%= replaypost.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %>  
                        </div>
                        <div class="col-sm-4">
                            <% if replaypost.updated_at != replaypost.created_at %><%# 投稿が編集されていれば編集日を表示する %>
                            編集日：<%= replaypost.updated_at.strftime("%Y年%m月%d日 %H:%M:%S") %>
                            <% end %>
                        </div>
                        <!-- <p>&nbsp;</p> -->
                        <div class="col-sm-12">
                            <p>
                            <%= replaypost.content %>
                            </p>
                        </div>
                        <!-- <p>&nbsp;</p> -->
                        <div class="col-sm-12">
                            <p>
                                <% if current_user.id == replaypost.user_id || current_user.admin? %><%# 投稿者本人のみ編集・削除を可能とする %>
                                    <%= link_to "返信を編集する",edit_replaypost_path(replaypost.id) %> | 
                                    <%#= link_to "削除", t, class: "btnlink btnlink-danger glyphicon glyphicon-trash",
                                        method: :delete, data: {confirm: "本当に削除してもいいですか？"} %>
                                    <%# destroyアクションにforum_idというパラメータを渡して、投稿削除後にこのページへリダイレクトさせる %>
                                    <%= link_to "削除", replaypost_path(replaypost.id, forum_id: @forum.id), class: "btnlink btnlink-danger glyphicon glyphicon-trash",
                                        method: :delete, data: {confirm: "本当に削除してもいいですか？"} %>
                                <% end %>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
            <%# end %>
            <%# 返信された書き込み ここまで ####################################################### %>

        </div><%# panel-body %>
    </div>
</div>
<% end %>
<%# 投稿された書き込み ここまで ####################################################### %>

<%# kaminariによるページネーション表示 %>
<div align="center">
    <%= paginate @resposts %>
</div>