config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, :controllers => {
  :sessions      => "users/sessions",
  :registrations => "users/registrations",
  :passwords     => "users/passwords",
  :omniauth_callbacks => "users/omniauth_callbacks"
  }

  get 'welcome/no_data' # ドメイン・バックリンクデータが存在しない場合の仮のペラページ
  get 'welcome/test' # テスト用

  
  resources :domains do
    member do
    end
    
    collection do
      post 'import'
      get 'nglist'
      get 'test'
    end
  end

  resources :backlinks do
    member do
    end
    
    collection do
      post 'import'
    end
  end

  resources :users do
    member do
      post 'pro_upgrade'
    end
    collection do
    end
  end
  
  resources :forums do
    collection do
      get 'message'
    end
  end
 
  resources :replayposts, only: [:new, :create, :edit, :update, :destroy]
  resources :resposts, only: [:show, :create, :edit, :update, :destroy]
  resources :forums, only: [:index, :show, :create, :update, :destroy]
  resources :manage, only: [:index]
  resources :users, only: [:index, :update, :destroy]
  
  resources :domains, only: [:index, :show]

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # before_action :domain_backlink_data_check # ここでこれを入れると無限ループになる。
  before_action :images_icons

  def index
    domain_backlink_data_check
     # @domains = Domain.all
    @domains_ok = Domain.where(ngcheck: "ok")
    @backlinks = Backlink.all
  end

  # Domain Backlink テーブルにデータがなければリダイレクト
  def domain_backlink_data_check
    if !Domain.exists? || !Backlink.exists?
      redirect_to welcome_no_data_path
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/import.html.erb
<h3>ドメインcsvインポート</h3>
<%= form_tag import_domains_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "インポート" %>
<% end %>

<hr>
<h3>バックリンクcsvインポート</h3>
<%= form_tag import_backlinks_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "インポート" %>
<% end %>
<hr>

<% if current_admin_user %>
  adminユーザーです。
<% else %>
  adminユーザーではありません。
<% end %>

<% if !Domain.exists? || !Backlink.exists? %>
  ないよ
<% else %>
  あるよ
<% end %>

app/views/welcome/index.html.erb
<% content_for(:head) do %>
    <%= stylesheet_link_tag    "domains", media: "all" %>
    <%= javascript_include_tag 'fixed_midashi.js' %>
    <%= javascript_include_tag 'jquery.tablesorter.min.js' %>
    <meta name="robots" content="index,nofollow,archive" />
    <script>
    $(function() {
      $('#sorter').tablesorter();
    });
    </script>
    <style type="text/css" media="screen">
    div.scroll_div { overflow: auto; }
    </style>
<% end %>

<% content_for(:body) do %>
  <body onLoad="FixedMidashi.create();">
<% end %>

<%= render 'shared/head_info' %>

<div class="domain_table">
<div class="scroll_div">
<table _fixedhead="rows:1; cols:1" id="sorter" class="table-bordered tablesorter">
  <thead>
    <tr>
      <th class="domain">ドメイン</th>
      <th class="pr">PR</th>
      <th class="blsyousai">BL<br />詳細</th>
      <th class="wayback">wayback</th>
      <th class="cheki">SEO<br />チェキ</th>
      <th class="index_count"><div class="tate-area" style="font-size:6pt;"><div class="tate-line">Index</div></div></th>
      <th class="dofollow_pr">Do<br />follow<br />PR数</th>
      <th class="nofollow_pr">No<br />follow<br />PR数</th>
      <th class="ip_bunsanritsu"><div class="tate-area" style="font-size:6pt;"><div class="tate-line">IP分散率</div></div></th>
      <th class="ip_unique_count"><div class="tate-area" style="font-size:6pt;"><div class="tate-line">重複しないIP数</div></div></th>
      <th class="ip_all_count"><div class="tate-area" style="font-size:6pt;"><div class="tate-line">全IP数</div></div></th>
      <th class="china"><div class="tate-area" style="font-size:6pt;"><div class="tate-line">中国リンク</div></div></th>
      <!-- <th><div class="tate-area" style="font-size:6pt;"><div class="tate-line">要注意</div></div></th> -->
      <th class="moz_rank"><div class="tate-area" style="font-size:6pt;"><div class="tate-line">MOZ・Rank</div></div></th>
      <th class="moz_da"><div class="tate-area" style="font-size:6pt;"><div class="tate-line">MOZ・DA</div></div></th>
      <th class="moz_pa"><div class="tate-area" style="font-size:6pt;"><div class="tate-line">MOZ・PA</div></div></th>
      <!-- <th><div class="tate-area" style="font-size:6pt;"><div class="tate-line">Ahr・DR</div></div></th> -->
      <!-- <th><div class="tate-area" style="font-size:6pt;"><div class="tate-line">Ahr・BLD</div></div></th> -->
      <th class="awy">AWY</th>
      <th>その他</th>
    </tr>
  </thead>
  <tbody>
  <% each_count = 0 %>
  <% @domains_ok.each do |d| %>
  
    <%# このドメインのバックリンクのURLを全て取得して一つにまとめる処理 ここから ###################################### %>
    <% backlinks = @backlinks.where(domain: d.name) %><%# このドメインnameを持つ全てのバックリンクオブジェクトを格納 %>
    <% backlink_urls = "" %><%# 変数を空として初期化 %>
    <% backlinks.each do |b| %>
      <% if b.bl_url.present? %>
        <% backlink_urls = backlink_urls + b.bl_url %><%# 文字列として繋げていき、最終的には一つにまとめる %>
      <% else %>
        <% backlink_urls = backlink_urls + "" %><%# 文字列として繋げていき、最終的には一つにまとめる %>
      <% end %>
    <% end %>
    <%# このドメインのバックリンクのURLを全て取得して一つにまとめる処理 ここまで ###################################### %>

    <%# バックリンクの種類判定の処理 ここから ############################################### %>
    <% etc = "" %><%# その他 %>
    <% wikipedia = "" %>
    <% china = "" %>
    <% or_ = "" %>
    <% facebook = "" %>
    <% twitter = "" %>
    <% gov = "" %>
    <% edu = "" %>
    <% museum = "" %>
    <% musicmoz = "" %>
    <% dmoz = "" %>
    <% youtube = "" %>
    <% linkedin = "" %>
    <% tumblr = "" %>
    <% myspace = "" %>
    <% plus_google = "" %>
    <% pinterest = "" %>
    <% matome_naver = "" %>
    <% okwave = "" %>

    <%# その他のまとめ ####################################################################################################### %>
    <% if backlink_urls.include?(".gr.") || backlink_urls.include?(".nic.") || backlink_urls.include?(".nytimes.com") ||
        backlink_urls.include?(".reuters.com") || backlink_urls.include?(".washingtonpost.com") || backlink_urls.include?(".nbc.com") %>
        <% etc = image_tag(@etc, hspace: 1) %>
    <% end %>

    <%# 政府機関のまとめ ####################################################################################################### %>
    <% if backlink_urls.include?(".gov/") || backlink_urls.include?(".gov.") || backlink_urls.include?(".go.") %>
        <% gov = image_tag(@gov, hspace: 1) %>
    <% end %>

    <%# 教育機関のまとめ ####################################################################################################### %>
    <% if backlink_urls.include?(".ac.") || backlink_urls.include?(".edu/") || backlink_urls.include?(".edu.") %>
        <% edu = image_tag(@edu, hspace: 1) %>
    <% end %>

    <% if backlink_urls.include?(".wikipedia.org") %><%# wikipedia %>
        <%# wikipedia = "[wikipedia]" %>
        <% wikipedia = image_tag(@wikipedia, hspace: 1) %>
    <% end %>

    <% if backlink_urls.include?(".cn/") || backlink_urls.include?(".cn.") %><%# 中国 china のみテーブルの別の列で表示させる %>
        <%# china = "[中国]" %>
        <% china = image_tag(@china, hspace: 1) %>
    <% end %>

    <% if backlink_urls.include?(".or.") %><%# 非営利法人 %>
        <%# or_ = "[.or]" %>
        <% or_ = image_tag(@corp, hspace: 1) %>
    <% end %>
    
    <% if backlink_urls.include?(".facebook.com") %>
        <%# facebook = "[facebook]" %>
        <% facebook = image_tag(@facebook, hspace: 1) %>
    <% end %>
    
    <% if backlink_urls.include?("//twitter.com") || backlink_urls.include?(".twitter.com") %>
        <%# twitter = "[twitter]" %>
        <% twitter = image_tag(@twitter, hspace: 1) %>
    <% end %>
    
    <% if backlink_urls.include?(".museum/") || backlink_urls.include?(".museum.") %>
        <%# museum = "[.museum]" %>
        <% museum = image_tag(@muse, hspace: 1) %>
    <% end %>
    
    <% if backlink_urls.include?("//musicmoz.org") || backlink_urls.include?(".musicmoz.org") %>
        <%# musicmoz = "[musicmoz]" %>
        <% musicmoz = image_tag(@musicmoz, hspace: 1) %>
    <% end %>
    
    <% if backlink_urls.include?("//dmoz.org") || backlink_urls.include?(".dmoz.org") %>
        <%# dmoz = "[dmoz]" %>
        <% dmoz = image_tag(@dmoz, hspace: 1) %>
    <% end %>
    
    <% if backlink_urls.include?(".youtube.com") %>
        <%# youtube = "[youtube]" %>
        <% youtube = image_tag(@youtube, hspace: 1) %>
    <% end %>
    
    <% if backlink_urls.include?(".linkedin.com") %>
        <%# linkedin = "[linkedin]" %>
        <% linkedin = image_tag(@linkedin, hspace: 1) %>
    <% end %>
    
    <% if backlink_urls.include?(".tumblr") %>
        <%# tumblr = "[tumblr]" %>
        <% tumblr = image_tag(@tumblr, hspace: 1) %>
    <% end %>
    
    <% if backlink_urls.include?("//myspace.com") %>
        <%# myspace = "[myspace]" %>
        <% myspace = image_tag(@myspace, hspace: 1) %>
    <% end %>
    
    <% if backlink_urls.include?("plus.google.com") %>
        <%# plus_google = "[googleplus]" %>
        <% plus_google = image_tag(@googleplus, hspace: 1) %>
    <% end %>
    
    <% if backlink_urls.include?(".pinterest.com") %>
        <%# pinterest = "[pinterest]" %>
        <% pinterest = image_tag(@pinterest, hspace: 1) %>
    <% end %>
    
    <% if backlink_urls.include?(".matome.naver.jp/") %>
        <%# matome_naver = "[naverまとめ]" %>
        <% matome_naver = image_tag(@naver, hspace: 1) %>
    <% end %>
    
    <% if backlink_urls.include?("okwave.jp/") %>
        <%# okwave = "[okwave]" %>
        <% okwave = image_tag(@okwave, hspace: 1) %>
    <% end %>
    
    <%# china のみテーブルの別の列で表示させる %>
    <% bl_syurui = etc + wikipedia + or_ + facebook + twitter + gov + edu + museum + musicmoz + dmoz + youtube + linkedin + tumblr + myspace + plus_google + pinterest + matome_naver + okwave %>
    <%# バックリンクの種類判定の処理 ここまで ############################################### %>


    <%# ドメインの一部を伏せ字にする処理 ここから ############################################### %>
    <% begin %>
        <% domain = d.name %>
        <% domain.downcase! %>
        <% str = domain %>
        <% p = str.index(".") %><%# カンマの位置 %>
        <% chikan_str = str[1..p-2] %><%# domain名の文字列の先頭末尾の文字列を除外して切り取る %>
        <% if chikan_str.length > 14 %><%# 置換する文字数が15個以上の場合は 伏せ文字*の数は15個とする %>
          <% fusemoji = "***************" %>
        <% else %>
          <% fusemoji = "*" %>
          <% chikan_str.length.times{ fusemoji = fusemoji + "*" } %>
        <% end %>
        <% domain = domain.gsub(chikan_str,fusemoji) %>
    <% rescue %><% domain = "エラー" %>
    <% end %>
    <%# ドメインの一部を伏せ字にする処理 ここまで ############################################### %>

    <tr>
      <td nowrap class="domain"><input type="checkbox" id="row_<%= each_count+1 %>" value="1" name="row_<%= each_count+1 %>"><%= domain %></td><%# name %>
      <td class="pr"><%= d.pr %></td><%# pr %>
      <td class="blsyousai"><%= link_to "BL詳細", "#", class: "" %></td><%# BL詳細 %>
      <td class="wayback"><%= link_to "wybk", "#", class: "" %></td><%# wayback %>
      <td class="cheki"><%= link_to "ﾁｪｷ", "#", class: "" %></td><%# seocheki %>
      <td class="index_count"><%= d.index_count %></td><%# index_count %>
      <td class="dofollow_pr"><%= d.dofollow_pr %></td><%# dofollow_pr %>
      <td class="nofollow_pr"><%= d.nofollow_pr %></td><%# nofollow_pr %>
      <td class="ip_bunsanritsu"><%= d.ip_bunsanritsu %>%</td><%# IP分散率 ip_bunsanritsu %>
      <td class="ip_unique_count"><%= d.ip_unique_count %></td><%# ip_unique_count 重複しないIP %>
      <td class="ip_all_count"><%= d.ip_all_count %></td><%# ip_all_count 全IP数 %>
      <td class="china"><%= china %></td><%# china 中国リンク %>
      <!-- <td></td> --><%# 要注意 %>
      <td class="moz_rank"><%= d.moz_rank %></td><%# moz_rank %>
      <td class="moz_da"><%= d.moz_da %></td><%# moz_da %>
      <td class="moz_pa"><%= d.moz_pa %></td><%# moz_pa %>
      <!-- <td>33</td> --><%# ahref dr %>
      <!-- <td>17</td> --><%# ahref bld %>
      <td class="awy"><%= d.awy %></td><%# awy %>
      <td nowrap><%= bl_syurui.html_safe %></td>
    </tr>
    <% each_count += 1 %>
  <% end %>
  </tbody>
</table>
</div>
</div>

<%= render 'shared/main_details' %>

app/views/welcome/no_data.html.erb
<p>Domainテーブルまたは、Backlinkテーブルにデータが存在しません。</p>

app/views/welcome/test.html.erb
<%= DateTime.now %>

<hr />

取得可：ai-tpm.com<br />
取得不可：stringzwingz.com<br />
http://www.webservicex.net/whois.asmx/GetWhoIS?HostName=

<% require 'open-uri' %>

<%############### .com .net の場合 ################################################################################ %>
<% check_domain = 'stringzwingz.com' %>
<%# check_domain = 'ai-tpm.com' %>
<% check_status = 'Status: ok' %>
<% check_str1 = 'Domain Name: ' %>
<% check_str2 = 'No match for "' %>

<% url = 'http://www.webservicex.net/whois.asmx/GetWhoIS?HostName=' + check_domain %>
<%# user_agentの偽装 %>
<% user_agent = 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36' %>
<% charset = nil %>
<% html = open(url, "User-Agent" => user_agent) do |f| %>
  <% charset = f.charset %><%# 文字種別を取得 %>
  <% f.read %>
<% end %>

<%= html %>
<br />

<% if html.downcase.include?(check_str1.downcase + check_domain.downcase) %><%# Domain Name: STRINGZWINGZ.COM %>
    <%# true なら取得不可 false なら取得可 %>
    <%= p = html.downcase.include?(check_status.downcase) %>
    <% if p = false %>
        <span style="background-color:#FFCACA;">取得可</span>
    <% else %>
        <span style="background-color:#FFCACA;">取得不可</span>
    <% end %>
<% end %>

<% if html.downcase.include?(check_str2.downcase + check_domain.downcase + '"') %><%# No match for "AI-TPM.COM" %>
    <span style="background-color:#FFCACA;">取得可</span>
<% end %>
<%############### .com .net の場合 ################################################################################ %>







<hr>





Respost.all:<%= Respost.all.inspect %>
<hr />
Respost.count:<%= Respost.count %>
<hr />
Replypost.all:<%= Replaypost.all.inspect %>
<hr />
Replaypost.count:<%= Replaypost.count %>
<hr />






<%= Rails.application.secrets.gmail_user_name %>

<% if user_signed_in? %>
    <% if current_user.admin? %>
        admin です。
    <% else %>
        admin ではないです。
    <% end %>
<% end %>


<hr>
<% if current_admin_user %>
  adminユーザーです。
<% else %>
  adminユーザーではありません。
<% end %>


<% @users = User.all %>
<%= @users.inspect %>

<hr>



@user = User.find(params[:id])
    @user.update_attributes = { :pmember = 'true'}