config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, :controllers => {
  :sessions      => "users/sessions",
  :registrations => "users/registrations",
  :passwords     => "users/passwords",
  :omniauth_callbacks => "users/omniauth_callbacks"
  }

  get 'welcome/no_data' # ドメイン・バックリンクデータが存在しない場合の仮のペラページ
  get 'welcome/test' # テスト用

  
  resources :domains do
    member do
    end
    
    collection do
      post 'import'
      get 'nglist'
      get 'test'
    end
  end

  resources :backlinks do
    member do
    end
    
    collection do
      post 'import'
    end
  end

  resources :users do
    member do
      post 'pro_upgrade'
    end
    collection do
    end
  end
  
  resources :forums do
    collection do
      get 'message'
    end
  end
 
  resources :replayposts, only: [:new, :create, :edit, :update, :destroy]
  resources :resposts, only: [:show, :create, :edit, :update, :destroy]
  resources :forums, only: [:index, :show, :create, :update, :destroy]
  resources :manage, only: [:index]
  resources :users, only: [:index, :update, :destroy]
  
  resources :domains, only: [:index, :show]

end

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#site-menu" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to "HOME", root_path, class: "navbar-brand" %>
			</div>
			<div class="collapse navbar-collapse" id="site-menu">
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "NGリスト", nglist_domains_path %></li>
					<li><%= link_to "フォーラム", forums_path %></li>
					
					<!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
					<% if user_signed_in? %> 
						<!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
						<!-- *_path はUserモデルを作成したときに、
						deviseにより自動で作成されてますので、rake routesで確認できます -->
						<!-- Logged in as <strong><%#= current_user.email %></strong>. -->

						<li><%= link_to "ドメイン一覧", domains_path %></li>
						<li><%= link_to 'ユーザー情報設定', edit_user_registration_path %></li>

						<% if current_user.promember? %>
						<% else %>
							<li><%= link_to '有料会員登録', pro_upgrade_user_path(id: current_user.id), method: :post %></li>
						<% end %>
						<li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
					<% else %>
						<li class="snsbtn"><%= link_to (image_tag @signintwitter), user_omniauth_authorize_path(:twitter) %></li>
						<li><%= link_to "サインイン", new_user_registration_path %></li>
						<li><%= link_to "ログイン", new_user_session_path %></li>
					<% end %>
					
					<% if user_signed_in? && current_user.admin? %>
						<li><%= link_to "管理画面", manage_index_path %></li>
						<li><%= link_to "会員一覧", users_path %></li>
						<li><%= link_to "rails_admin", rails_admin.dashboard_path, target: "_blank" %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>
</header>


<% if user_signed_in? %> 
	<p><strong>
	<% if current_user.admin? %>
		admin:
	<% end %>
	<%= current_user.email %> 
	handlename:
	<% if current_user.handlename.present? %>
		<%= current_user.handlename %>
	<% else %>
		未設定
	<% end %>
	<% if current_user.promember? %>
		有料会員
	<% else %>
		無料会員
	<% end %>
	</strong>でログイン中</p>
<% else %>
<% end %>

<%= link_to "testページ", welcome_test_path, target: "_blank" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Olddomain</title>
    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <% if content_for?(:head) %>
      <%= yield :head %>
    <% end %>
  </head>

  <% if content_for?(:body) %>
    <%= yield :body %>
  <% else %>
    <body>
  <% end %>

  <div id="wrap"> 
    <div class="container">
      <% if content_for?(:header) %>
        <%= yield :header %>
      <% else %>
        <%= render 'layouts/header' %>
      <% end %>
    
    <div id="notice">
      <% flash.each do |message_type, message| %><!-- フラッシュメッセージを表示ここから -->
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %><!-- フラッシュメッセージを表示ここまで -->
    </div>
    
    <article>
      <section>
        <%= yield %>
      </section>
    </article>
    
    </div><!-- container -->
  </div><!-- wrap -->
  
  <footer id="footer">
    <div class="container">
      <div class="copyright">
        <p>
          <br/>Copyright (C) サイトタイトル All Rights Reserved.
        </p>
      </div>
    </div>
  </footer>
  
  <!-- フラッシュメッセージ消す -->
  <script>
    $(function() {
      setTimeout(function() {
        $('#notice').fadeOut("slow");
      }, 10000);
    });
  </script>
  
  <% if content_for?(:footer_js) %>
    <%= yield :footer_js %>
  <% end %>
  
  </body>
</html>